BusinessManagement/views/admin.py
import io
import os
import csv
from flask import Blueprint, render_template, request, redirect, flash
from werkzeug.utils import secure_filename
from sql.db import DB
import traceback
admin = Blueprint('admin', __name__, url_prefix='/admin')

@admin.route("/import", methods=["GET","POST"])
def importCSV():
    if request.method == "POST":
        if 'file' not in request.files:
            return redirect(request.url)
        file = request.files['file']
        # If the user does not select a file, the browser submits an
        # empty file without a filename.
        if file.filename == '':
            flash('No selected file', "warning")
            return redirect(request.url)
        # TODO importcsv-1 check that it's a .csv file, return a proper flash message if it's not
        #ucid - pk639
        #date 12/04/2022
        if os.path.splitext(file.filename)[1] != ".csv":
            flash('Invalid File Type, The file selected is not a .csv file', "warning")
            return redirect(request.url)
        if file and secure_filename(file.filename):
            companies = []
            employees = []
            company_query = """
            INSERT INTO IS601_MP2_Companies (name, address, city, country, state, zip, website)
                        VALUES (%(name)s, %(address)s, %(city)s, %(country)s, %(state)s, %(zip)s, %(website)s)
                        ON DUPLICATE KEY UPDATE address = %(address)s, city = %(city)s, country=%(country)s, state=%(state)s, zip=%(zip)s, website=%(website)s 
            """
            employee_query = """
             INSERT INTO IS601_MP2_Employees (first_name, last_name, email, company_id)
                        VALUES (%(first_name)s, %(last_name)s, %(email)s, (SELECT id FROM IS601_MP2_Companies WHERE name = %(company_name)s LIMIT 1))
                        ON DUPLICATE KEY UPDATE first_name=%(first_name)s, last_name = %(last_name)s, email = %(email)s, company_id = (SELECT id FROM IS601_MP2_Companies WHERE name = %(company_name)s LIMIT 1)
            """
            # Note: this reads the file as a stream instead of requiring us to save it
            stream = io.TextIOWrapper(file.stream._file, "UTF8", newline=None)
            # TODO importcsv-2 read the csv file stream as a dict
             #ucid - pk639
            #date 12/04/2022
            for row in csv.DictReader(stream, delimiter=','):
                # print(row) #example
                # TODO importcsv-3 extract company data and append to company list as a dict only with company data
                    #ucid - pk639
                    #date 12/04/2022
                if row["company_name"] and row["address"] and row["city"] and row["state"] and row["zip"] and row["web"] and row["country"]:
                    companies.append({"name" : row["company_name"],  "address" :  row["address"], "city" : row["city"], "state" : row["state"], "country" : row["country"], "zip": row["zip"], "website" : row["web"]})

                # TODO importcsv-4 extract employee data and append to employee list as a dict only with employee data
                    #ucid - pk639
                    #date 12/04/2022
                if row["first_name"] and row["last_name"] and row["email"] and row["company_name"]:
                    employees.append({"first_name" : row["first_name"],  "last_name" :  row["last_name"], "email" : row["email"], "company_name" : row["company_name"]})
               
            if len(companies) > 0:
                print(f"Inserting or updating {len(companies)} companies")
                try:
                    result = DB.insertMany(company_query, companies)
                    # TODO importcsv-5 display flash message about number of companies inserted
                        #ucid - pk639
                        #date 12/04/2022
                    flash(f"Inserted {len(companies)} companies records successfully!", "success")
                except Exception as e:
                    traceback.print_exc()
                    flash("There was an error loading in the csv data", "danger")
            else:
                # TODO importcsv-6 display flash message (info) that no companies were loaded
                 #ucid - pk639
                 #date 12/04/2022
                flash("No companies records were loaded", "danger")
            if len(employees) > 0:
                print(f"Inserting or updating {len(employees)} employees")
                try:
                    result = DB.insertMany(employee_query, employees)
                    # TODO importcsv-7 display flash message about number of employees loaded
                     #ucid - pk639
                     #date 12/04/2022
                    flash(f"Inserted {len(employees)} employees records successfully!", "success")
                except Exception as e:
                    traceback.print_exc()
                    flash("There was an error loading in the csv data", "danger")
            else:
                 # TODO importcsv-8 display flash message (info) that no companies were loaded
                  #ucid - pk639
                  #date 12/04/2022
                flash("No employees records were loaded", "danger")
    return render_template("upload.html")

BusinessManagement/views/company.py
from flask import Blueprint, redirect, render_template, request, flash, url_for
from sql.db import DB
from werkzeug.datastructures import MultiDict
from views.forms import CompanyForm
company = Blueprint('company', __name__, url_prefix='/company')

@company.route("/search", methods=["GET"])
def search():
    rows = []
    # DO NOT DELETE PROVIDED COMMENTS
    # TODO search-1 retrieve id, name, address, city, country, state, zip, website, employee count for the company
    # don't do SELECT *
    query = "SELECT c.id, c.name, c.address, c.city, c.country, c.state, c.zip, c.website, COUNT(e.id) AS Employees from IS601_MP2_Companies c LEFT JOIN IS601_MP2_Employees e ON e.company_id = c.id WHERE 1=1"
    args = [] # <--- append values to replace %s placeholders
    allowed_columns = ["name", "city", "country", "state"]

    allowed_columns_tuples = [(c, c) for c in allowed_columns]
    # TODO search-2 get name, country, state, column, order, limit request args
    name = request.args.get("name")
    country = request.args.get("country")
    state = request.args.get("state")
    column = request.args.get("column")
    order = request.args.get("order")
    limit = request.args.get("limit", 10)

    # TODO search-3 append a LIKE filter for name if provided
    if name:
        query += " AND name like %s"
        args.append(f"%{name}%")

    # TODO search-4 append an equality filter for country if provided
    if country:
        query += f" AND country = '{country}'"

    # TODO search-5 append an equality filter for state if provided
    if state:
        query += f" AND state = '{state}'"

    query += " GROUP BY c.id"

    # TODO search-6 append sorting if column and order are provided and within the allows columsn and allowed order asc,desc
    if column and order:
        print(column, order)
        if column in allowed_columns \
            and order in ["asc", "desc"]:
            query += f" ORDER BY {column} {order}"

    # TODO search-7 append limit (default 10) or limit greater than 1 and less than or equal to 100
    if limit and int(limit) > 0 and int(limit) <= 100:
        query += " LIMIT %s"
        args.append(int(limit))

    # TODO search-8 provide a proper error message if limit isn't a number or if it's out of bounds
    try:
        type(int(limit))
    except Exception as e:
        flash("ValueError, the limit entered is not a number", "error")

    if not int(limit) > 0 and int(limit) <= 100:
        flash("Limit entered is out of bounds. Limit should be in between 0 and 100", "error")
    
    print("query",query)
    print("args", args)
    try:
        result = DB.selectAll(query, *args)
        if result.status:
            rows = result.rows
    except Exception as e:
        # TODO search-9 make message user friendly
        flash(f"Following exception occured while fetching the company list:{str(e)}", "danger")
    # hint: use allowed_columns in template to generate sort dropdown
    return render_template("list_companies.html", rows=rows, allowed_columns=allowed_columns_tuples)

@company.route("/add", methods=["GET","POST"])
def add():
    form = CompanyForm(request.form)
    if request.method == "POST":
        # TODO add-1 retrieve form data for name, address, city, state, country, zip, website
        #pk 639 
        #12/4/2022
        name = form.name.data
        address = form.address.data
        city = form.city.data
        zipcode = form.zip.data
        website = form.website.data
        state = request.form.get("state", None)
        country = request.form.get("country", None)
        # TODO add-2 name is required (flash proper error message)
        #pk 639 
        #12/4/2022
        if name == '' or name == None:
            flash("Name is required", "danger")
            return redirect("add")
        # TODO add-3 address is required (flash proper error message)
        #pk 639 
        #12/4/2022
        if address == '' or address == None:
            flash("Address is required", "danger")
            return redirect("add")
        # TODO add-4 city is required (flash proper error message)
        #pk 639 
        #12/4/2022
        if city == '' or city == None:
            flash("City is required", "danger")
            return redirect("add")
        # TODO add-5 state is required (flash proper error message)
        #pk 639 
        #12/4/2022
        if state == '' or state == None:
            flash("State is required", "danger")
            return redirect("add")
        # TODO add-6 country is required (flash proper error message)
        #pk 639 
        #12/4/2022
        if country == '' or country == None:
            flash("Country is required", "danger")
            return redirect("add")
        # TODO add-7 website is not required
        #pk 639 
        #12/4/2022
        if website == '':
            website = 'N/A'
        
        has_error = False # use this to control whether or not an insert occurs
        

        if not has_error:
            try:
                result = DB.insertOne("""
                INSERT INTO IS601_MP2_Companies (name, address, city, country, state, zip, website)
                            VALUES (%(name)s, %(address)s, %(city)s, %(country)s, %(state)s, %(zip)s, %(website)s)
                            ON DUPLICATE KEY UPDATE name=%(name)s, address = %(address)s, city = %(city)s, country = %(country)s, state = %(state)s, zip = %(zip)s, website = %(website)s
                """, {'name': name, 'address': address, 'city': city, 'country': country, 'state': state, 'zip': zipcode, 'website': website}) # <-- TODO add-8 add query and add arguments
                if result.status:
                    flash("Added Company", "success")
            except Exception as e:
                # TODO add-9 make message user friendly
                 #pk 639 
                 #12/4/2022
                flash(f" Following exception occured while adding the company: {str(e)}", "danger")
        
    return render_template("add_company.html", form=form)

@company.route("/edit", methods=["GET", "POST"])
def edit():
    form = CompanyForm(request.form)
    # TODO edit-1 request args id is required (flash proper error message)
    id = request.args.get("id")
    if id is None:
        flash("ID is missing", "danger")
        return redirect("company.search")
    else: # TODO update this for TODO edit-1
        if request.method == "POST":
            # TODO edit-2 retrieve form data for name, address, city, state, country, zip, website
            name = form.name.data
            address = form.address.data
            city = form.city.data
            zipcode = form.zip.data
            website = form.website.data
            state = request.form.get("state", None)
            country = request.form.get("country", None)
            # TODO edit-3 name is required (flash proper error message)
            if name == '' or name == None:
                flash("Name is required", "danger")
                return redirect("add")
            # TODO edit-4 address is required (flash proper error message)
            if address == '' or address == None:
                flash("Address is required", "danger")
                return redirect("add")
            # TODO edit-5 city is required (flash proper error message)
            if city == '' or city == None:
                flash("City is required", "danger")
                return redirect("add")
            # TODO edit-6 state is required (flash proper error message)
            if state == '' or state == None:
                flash("State is required", "danger")
                return redirect("edit")
            # TODO edit-7 country is required (flash proper error message)
            if country == '' or country == None:
                flash("Country is required", "danger")
                return redirect("edit")
            # TODO edit-8 website is not required
            if website == '' or website == None:
                website = 'N/A'
            # 
            # note: call zip variable zipcode as zip is a built in function it could lead to issues
            data = [name, address, city, state, country, zipcode, website]
            data.append(id)
            try:
                # TODO edit-9 fill in proper update query
                result = DB.update("""
                UPDATE IS601_MP2_Companies SET name = %s, address = %s, city = %s, state = %s, country = %s, zip = %s, website = %s WHERE id = %s
                """, *data)
                if result.status:
                    flash("Updated record", "success")
            except Exception as e:
                # TODO edit-10 make this user-friendly
                flash(f" Following exception occured while updating the company: {str(e)}", "danger")
        try:
            # TODO edit-11 fetch the updated data
            result = DB.selectOne("SELECT name, address, city, state, country, zip, website FROM IS601_MP2_Companies WHERE id = %s", id)
            if result.status:
                row = result.row
                form.process(MultiDict(row))
                
        except Exception as e:
            # TODO edit-12 make this user-friendly
            flash(f" Following exception occured while fetching the updated company record: {str(e)}", "danger")
    # TODO edit-13 pass the company data to the render template
    return render_template("edit_company.html", form=form, state=row['state'], country=row['country'])

@company.route("/delete", methods=["GET"])
def delete():
    #pk639
    #12/4/2022
    # TODO delete-1 delete company by id (unallocate any employees)
    # TODO delete-2 redirect to company search
    # TODO delete-3 pass all argument except id to this route
    # TODO delete-4 ensure a flash message shows for successful delete
    id = request.args.get("id")
    args = {**request.args}
    if id:
        try:
            result = DB.delete("DELETE FROM IS601_MP2_Companies WHERE id = %s", id)

BusinessManagement/views/geography.py
import pycountry
import json
from flask import Blueprint, request

geo = Blueprint("geo", __name__, url_prefix='/geo')
# TODO DO NOT EDIT
# these are javascript endpoints used from country_state_selector.html
@geo.route("/countries")
def countries():
    # extract just the data we need for our <select> options
    countries = map(lambda c: {"code": c.alpha_2, "name": c.name},list(pycountry.countries))
    return json.dumps(list(countries))

@geo.route("/states")
def states():
    # extract just the data we need for our <select> options
    status = list(map(lambda s: {"name": s.name, "code": s.code.split("-")[1]}, 
        list(pycountry.subdivisions.get(country_code=request.args.get('country_code', 'US')))))
    return json.dumps(status)

BusinessManagement/views/index.py
from flask import Blueprint, render_template
home = Blueprint('home', __name__, url_prefix='/')

# TODO DO NOT EDIT
@home.route('/')
def index():
    return render_template("index.html")

BusinessManagement/templates/add_company.html
{% extends "layout.html" %}
{% block title %}Add Company{% endblock %}
{% block content %}
{% from "_formhelpers.html" import render_field %}
<div class="container-fluid">
    <div class="h1 text-center m-3">Add Company</div>
    <div class="card mx-auto  mb-4" style="max-width: 500px;">
        <div class="card-body">
            <form method="POST">
                {#
                generate fields with proper types for
                name
                address
                city
                website
                #}
                {{ form.hidden_tag() }}
                {{render_field(form.name)}}
                {{render_field(form.address)}}
                {{render_field(form.city)}}
                {# use this for country/state selection #}
                {% include "country_state_selector.html" %}
                {{render_field(form.zip)}}
                {{render_field(form.website)}}
                <input type="submit" class="btn btn-primary" value="Save Company" />
            </form>
        </div>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/add_employee.html
{% extends "layout.html" %}
{% block title %}Add Employee{% endblock %}
{% block content %}
{% from "_formhelpers.html" import render_field %}
<div class="container-fluid">
    <div class="h1 text-center m-3">Add Employee</div>
    <div class="card mx-auto" style="max-width: 500px;">
        <div class="card-body">
            <form method="POST">
                {#
                generate fields with proper types for
                first_name
                last_name
                email
                #}
                {{ form.hidden_tag() }}
                {{render_field(form.first_name)}}
                {{render_field(form.last_name)}}
                {{render_field(form.email)}}
                {# use the below for company selection #}
                <div class="col-12 mb-3">
                    <label class="form-label" for="company">Company</label>
                    {% include "company_dropdown.html" %}
                </div>
                <input type="submit" class="btn btn-primary mb-3" value="Save Employee" />
            </form>
        </div>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/company_dropdown.html
{% set comps = get_companies() %}
{# can set val prior to inclusion to prefill this field #}
{# TODO DO NOT EDIT #}
<select class="form-select" name="company" value="{{val or ''}}">
    <option value="">No Company</option>
    {% for c in comps %}
    {# example of using external data setting and casting #}
    <option {{'selected' if val|string==c['id']|string}} value="{{c['id']}}">{{c['name']}}</option>
    {% endfor %}
</select>

BusinessManagement/templates/country_state_selector.html
{# TODO DO NOT EDIT #}
{% set c = request.args.get("country", request.form.get("country", country or '')) %}
{% set s = request.args.get("state", request.form.get("state", state or '')) %}
{% if layout and layout == 'horizontal' %}
{# version for filter forms #}
<div class="col-12">
    <label class="visually-hidden" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{c}}"
        onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="col-12">
    <label class="visually-hidden" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{s}}">
        <option value="">Select State...</option>
    </select>
</div>
{% else %}
{# version for add/edit forms #}
<div class="form-group mb-3">
    <label class="form-label" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{c}}"
        onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="form-group mb-3">
    <label class="form-label" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{s}}">
        <option value="">Select State...</option>
    </select>
</div>
{% endif %}
<script>
    //gets called on page load and when the country selection changes
    const fetchStates = (country) => {
        //use jinja to return a string in the html template
        //this string will be as if we did let state = "whatever"
        let state = "{{s}}";
        console.log("fetching", country);
        fetch(`{{url_for('geo.states')}}?country_code=${country}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='state']");

                //if we had options, "clear" it to be the default option
                //so appending works
                if (ele.children.length > 1) {
                    ele.innerHTML = `<option value="">Select State...</option>`;
                }
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args state
                ele.value = state;
            });
    }
    window.addEventListener("load", () => {
        //use jinja to return a string in the html template
        //this string will be as if we did let country = "whatever"
        let country = "{{c}}";
        //get the country list from the endpoint
        fetch(`{{url_for('geo.countries')}}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='country']");
                ele.value = "";//clear the value so "onchange" works
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args country
                ele.value = country;
            })
            .finally(() => {
                //get the state list from the endpoint
                fetchStates(country);
            });
    });
</script>

BusinessManagement/templates/flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class=flashes>
    {% for category, message in messages %}
    <div class="alert alert-{{ category or 'info' }}" role="alert">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}

BusinessManagement/templates/index.html
{% extends "layout.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1 text-center text-warning">Ducks In a Row</div>
    <div class="w-50 mx-auto bg-light text-center caption border">At Ducks In A Row, we help
        organize your
        companies and
        employees all in one simple dashboard.</div>
    <div class="lead">Brought to you by Kota Pavan kumar (pk639) from section IS601-005
        {# TODO replace my name with your first name #}
        {# TODO replace my ucid with your ucid #}
        {# TODO replace both with your section (i.e., 005, 007, etc) #}
    </div>
</div>
{% endblock %}

BusinessManagement/templates/layout.html
<!doctype html>
<html>

<head>
    {% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
    <style>
        .footer {
            display: block;
        }

        .header {
            top: 0;
            height: 60px;
            line-height: 60px;
        }
    </style>
    <title>{% block title %}{% endblock %} - MP2</title>
    {% endblock %}
</head>

<body>
    <div id="header">
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                {# TODO replace my ucid mt85 with your ucid #}
                <a class="navbar-brand" href="{{url_for('home.index')}}">DIAR-pk639</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                {# TODO fill in the relevant hrefs using url_for() #}
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <!-- company dropdown nav -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Company
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{url_for('company.search')}}">Search</a></li>
                                <li><a class="dropdown-item" href="{{url_for('company.add')}}">Add</a></li>

                            </ul>
                        </li>
                        <!-- employee dropdown nav -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Employee
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{url_for('employee.search')}}">Search</a></li>
                                <li><a class="dropdown-item" href="{{url_for('employee.add')}}">Add</a></li>
                            </ul>
                        </li>
                        <!-- admin dropdown nav -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Admin
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{url_for('admin.importCSV')}}">Import</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% include 'flash.html' %}
    </div>
    <div id="content" class="overflow-scroll" style="height: 84vh">
        {% block content %} {% endblock %}
    </div>
    <div id=" footer" class="footer mt-auto py-3 bg-light text-center fixed-bottom">
        <div class="container">
            {% block footer %}
            <span>Business Management &copy; Copyright 2022.</span>
            {% endblock %}
        </div>
    </div>
</body>

</html>

BusinessManagement/templates/list_companies.html
{% extends "layout.html" %}
{% block title %}Company Directory{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1 text-center m-4">Company Directory</div>
    {# TODO
    build a horizontal filter/sort form with
    name (company name)
    country/state (provided)
    sort/order (using allowed_columns and provided partial template)
    limit
    ensure all fields prefill with request arg data if provided
    #}
    <form class="row row-cols-lg-auto g-3 mb-4 align-items-end" method="GET">
        <div class="col-12" style="max-width: 18%;">
            <label class="form-label visually-hidden" for="name">Name</label>
            <input type="text" name="name" class="form-control" id="name" placeholder="Name"
                value="{{request.args.get('name') or ''}}">
        </div>
        {% with layout = "horizontal" %}
            {% include "country_state_selector.html" %}
        {% endwith %}
        {% with cols = allowed_columns %}
            {% include "sort_filter.html" %}
        {% endwith %}
        <div class="col-12" style="max-width: 18%;">
            <label class="form-label visually-hidden" for="limit">Limit</label>
            <input type="number" name="limit" class="form-control" id="limit" placeholder="Limit" min="0" max="100"
                value="{{request.args.get('limit') or 10}}">
        </div>
        
        <div class="col-12">
            <input type="submit" class="btn btn-primary" value="Filter" />
        </div>
        <div class="col-12">
            <a href="?" class="btn btn-secondary">Reset</a>
        </div>
    </form>
    <div class="table-responsive">
    <table class="table">
        {% if rows and rows|length > 0 %}
        <thead>
            <tr class="text-capitalize">
                {# generate th tags for each column to display #}
                {# IMPORTANT use table column names as the headings, replace _ with space #}
                {% for r in rows[0] %}
                    <th>{{r | replace("_", " ")}}</th>
                {% endfor %}
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {# generate tr with td tags for each piece of data #}
            {# if the td is for website, display it as a link where the text is "website" and the url is the
            website url #}
            {# in the last column add the following
            a view button that passes the company id to employee search (this will be a company employee
            directory) also pass company_name as an argument
            an edit button that passes the company id to company edit
            a delete button that passes the company id and the request args to the company delete route
            #}
            {% for r in rows %}
                <tr>
                    {% for col, value in r.items() %}
                        {% if col == 'website' and value != 'N/A' %}
                            <td><a href="{{value}}" class="link-primary" target="_blank">Website</a></td>
                        {% else %}
                            <td>{{value}}</td>
                        {% endif %}
                    {% endfor %}
                    <td style="max-width: 18%;">
                        <a href="{{url_for('employee.search', company=r.get('id'), company_name=r.get('name'))}}" class="btn btn-primary btn-sm">View</a>
                        <a href="{{url_for('company.edit', id=r.get('id'))}}" class="btn btn-secondary btn-sm">Edit</a>
                        <a href="{{url_for('company.delete', id=r.get('id'), **request.args)}}"
                            class="btn btn-danger btn-sm">X</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
        {% else %}
        <tbody>
            <tr>
                <td colspan="100%">No results to show</td>
            </tr>
        </tbody>
        {% endif %}
    </table>
    </div>
</div>
{% endblock %}